# Generated by Django 2.2.1 on 2019-05-27 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_id', models.CharField(max_length=12)),
                ('verified', models.BooleanField(default=False)),
                ('reputation', models.IntegerField(default=1)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_url', models.CharField(default='wkL063d9gAGCnPv', max_length=15)),
                ('comment', models.TextField()),
                ('score', models.IntegerField(default=0)),
                ('time_posted', models.IntegerField(default=0)),
                ('accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100)),
                ('file_name', models.TextField()),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('views', models.IntegerField(default=0)),
                ('answer_count', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=255)),
                ('time_added', models.IntegerField(default=0)),
                ('has_media', models.BooleanField(default=False)),
                ('solved', models.BooleanField(default=False)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
            options={
                'ordering': ['time_added'],
            },
        ),
        migrations.CreateModel(
            name='ViewerIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=32)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ViewerAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('associated_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUpvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
                ('upvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Media')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDownvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUpvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Comment')),
                ('upvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.CreateModel(
            name='CommentMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Comment')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Media')),
            ],
        ),
        migrations.CreateModel(
            name='CommentDownvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Comment')),
                ('downvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account'),
        ),
    ]
