# Generated by Django 2.2 on 2019-05-01 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='OWfZr0hBZe8QQ6x', max_length=15),
        ),
    ]
