# Generated by Django 2.2.1 on 2019-06-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='Yp2I60jeTjESNz8', max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
