# Generated by Django 2.1.7 on 2019-03-26 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0002_auto_20190326_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='EJYzMeK8ss3eZYw', max_length=15),
        ),
    ]
