# Generated by Django 2.1.7 on 2019-03-26 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0003_auto_20190326_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='83RDxC32CeoWlXo', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(),
        ),
    ]
