# Generated by Django 2.1.7 on 2019-03-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0005_auto_20190326_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='nuQOC8jNP6g8wZd', max_length=15),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.FloatField(default=0.0),
        ),
    ]
