# Generated by Django 2.1.7 on 2019-03-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0006_auto_20190327_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='9v0CUz3wFK0fURQ', max_length=15),
        ),
    ]
