# Generated by Django 2.1.7 on 2019-03-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0007_auto_20190327_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='NDVyHpjT5VzzTZO', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
