# Generated by Django 2.1.7 on 2019-04-07 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0009_auto_20190327_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(default=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
                ('upvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='eQiYpGLYMmzryWe', max_length=15),
        ),
    ]
