# Generated by Django 2.1.7 on 2019-04-08 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0010_auto_20190406_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentDownvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CommentUpvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionDownvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionUpvotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Post')),
                ('upvoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='question',
        ),
        migrations.RemoveField(
            model_name='upvotes',
            name='upvoter',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='qCGNLKQwvfD8zVn', max_length=15),
        ),
        migrations.DeleteModel(
            name='Upvotes',
        ),
        migrations.AddField(
            model_name='commentupvotes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Comment'),
        ),
        migrations.AddField(
            model_name='commentupvotes',
            name='upvoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account'),
        ),
        migrations.AddField(
            model_name='commentdownvotes',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Comment'),
        ),
        migrations.AddField(
            model_name='commentdownvotes',
            name='downvoter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='overflow.Account'),
        ),
    ]
