# Generated by Django 2.1.7 on 2019-04-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0011_auto_20190408_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='selLDeWLh5U3Nu1', max_length=15),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
