# Generated by Django 2.1.7 on 2019-04-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0012_auto_20190408_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='aaWq8pcMpk6RHLy', max_length=15),
        ),
    ]
