# Generated by Django 2.1.7 on 2019-04-09 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0014_auto_20190409_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='MJk6CXlbDdg0Ewf', max_length=15),
        ),
    ]
