# Generated by Django 2.2 on 2019-04-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overflow', '0015_auto_20190409_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_url',
            field=models.CharField(default='NTyxc0ggE4mJzyv', max_length=15),
        ),
    ]
